### ISSUE TITLE
Mobile app support

### ISSUE THREAD

**Issue by jeroenvollenbrock** [Timvdv/homey-random-cat-fact#1]
Asking for a random cat fact through the Homey smartphone app results in a cat fact sounding from the internal Homey speaker instead of the smartphone. Please update to the new smartphone-friendly speech api.

**Comment by Timvdv** [comment]
@jeroenvollenbrock Did some updates, don't have an Android phone. Can you tell me if it's better now?

**Comment by jeroenvollenbrock** [comment]
The app still only speaks through the Homey speaker, you should use speech.say instead of Homey.manager('speech-output').say, in order to maintain the speech session. See https://developers.athom.com/library/speech/ for more details.

**Comment by Timvdv** [comment]
@jeroenvollenbrock Thats pretty weird, I do believe you but in the example on the documentation page you linked they used `Homey.manager('speech-output').say( "The weather today is amazing!" );` Which is the same way as I'm using it. And few lines down they use `speech.say( __("ok") );` which is the other way.. 

It's a bit weird that they use both ways in one file without further explanation

**Comment by jeroenvollenbrock** [comment]
Hi Tim, we've updated our documentation based on your feedback and explained the difference between the two ways to make Homey say something.
